### ISSUE TITLE
R.I.P </3

### ISSUE THREAD

**Issue by Hail2Hydra** [jetkai/proxy-list#5]
Come Back To The Dark Side Please :)

**Comment by Hail2Hydra** [comment]
[Updated-13/02/2022-21:29:03]
 2 hours ago

proxies.txt - 0 lines (0 sloc)  0 Bytes

**Comment by jetkai** [comment]
@Hail2Hydra - Thanks for the report! ❤️

**Problem:** Parsing issue when the function "**formatIp**" is fed an IP address which is not in the correct format -> 127:0:0:1:80 instead of 127.0.0.1:80. No catch exception to skip.

Currently looking into this (has only cropped up a few times).

https://github.com/jetkai/ProxyBuilder/blob/cd7a20f42cac1975e1de2c06ed08741ecfa7ca2d/src/main/kotlin/spb/net/proxy/ProxyGrabber.kt#L69-L80

**Comment by Hail2Hydra** [comment]
<3 thank you so much for the work your doing and for Fixing it all in a fast time frame Youre Great
