### ISSUE TITLE
Upgrading Checker - Possible Downtime

### ISSUE THREAD

**Issue by jetkai** [jetkai/proxy-list#6]
Currently working on pushing a large update to the checker which will improve the performance and reliability of this list. At the moment, the current checker can fail to produce a full list - this has since been resolved in the latest update.

Expected to be pushed by EOD.

**Comment by Hail2Hydra** [comment]
@jetkai 

Ladies & Gentleman ITS ALIVE !! <Insert Evil Laugh Here >  ^_^

Glad to See You Back ! Im so addicted to the proxies!!! it had me going through withdrawals =( 

Also Thanks for the Update <3

**Comment by jetkai** [comment]
>  @jetkai 
> 
> 
> 
> Ladies & Gentleman ITS ALIVE !! (Insert Evil Laugh Here )  ^_^
> 
> 
> 
> Glad to See You Back ! Im so addicted to the proxies!!! it had me going through withdrawals =( 
> 
> 
> 
> Also Thanks for the Update <3

The old build is still running at the moment as I haven't had time to push the latest build so this will still fail and might not produce as many proxies.

I should be able to finish it off by the end of this week.

**Comment by Hail2Hydra** [comment]
I appreciate the Reply and the hard work your putting into this Repo !
I haven't had any trouble with Production of less Proxies !
Even if there was still a few less it wouldn't matter because the liveness of your proxies id rather have 300 Live Proxies instead of 2000 Proxies Dead !<- Just an example not actual numbers from repo

**Comment by Hail2Hydra** [comment]
> > @jetkai
> > Ladies & Gentleman ITS ALIVE !! (Insert Evil Laugh Here )  ^_^
> > Glad to See You Back ! Im so addicted to the proxies!!! it had me going through withdrawals =(
> > Also Thanks for the Update <3
> 
> The old build is still running at the moment as I haven't had time to push the latest build so this will still fail and might not produce as many proxies.
> 
> I should be able to finish it off by the end of this week.
I appreciate the Reply and the hard work your putting into this Repo !
I haven't had any trouble with Production of less Proxies !
Even if there was still a few less it wouldn't matter because the liveness of your proxies id rather have 300 Live Proxies instead of 2000 Proxies Dead !<- Just an example not actual numbers from repo

**Comment by jetkai** [comment]
This change has been pushed, currently monitoring.
